
services:
  bot-mail-netflix:
    build: .
    container_name: bot-mail-netflix
    restart: unless-stopped
    environment:
      - IMAP_USER=${IMAP_USER}
      - IMAP_PASS=${IMAP_PASS}
      - IMAP_HOST=${IMAP_HOST:-imap.gmail.com}
      - IMAP_PORT=${IMAP_PORT:-993}
    env_file:
      - .env
    # lance index.js toute les minutes
    command: sh -c "while true; do node index.js; sleep 60; done"
    volumes:
      - ./logs:/app/logs
